/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as JefeZonaRouteRouteImport } from './routes/jefe-zona/route'
import { Route as RecepcionRouteRouteImport } from './routes/recepcion/route'
import { Route as VigilanteRouteRouteImport } from './routes/vigilante/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCatalogoRouteRouteImport } from './routes/admin/catalogo/route'
import { Route as AdminDineroRouteRouteImport } from './routes/admin/dinero/route'
import { Route as AdminOperacionRouteRouteImport } from './routes/admin/operacion/route'
import { Route as AdminPersonalRouteRouteImport } from './routes/admin/personal/route'
import { Route as JefeZonaIndexRouteImport } from './routes/jefe-zona/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as RecepcionIndexRouteImport } from './routes/recepcion/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as VigilanteIndexRouteImport } from './routes/vigilante/index'
import { Route as AdminCatalogoIndexRouteImport } from './routes/admin/catalogo/index'
import { Route as AdminConfiguracionIndexRouteImport } from './routes/admin/configuracion/index'
import { Route as AdminDineroIndexRouteImport } from './routes/admin/dinero/index'
import { Route as AdminOperacionIndexRouteImport } from './routes/admin/operacion/index'
import { Route as AdminPersonalIndexRouteImport } from './routes/admin/personal/index'
import { Route as JefeZonaAsistenciaIndexRouteImport } from './routes/jefe-zona/asistencia/index'
import { Route as JefeZonaCajaIndexRouteImport } from './routes/jefe-zona/caja/index'
import { Route as JefeZonaInventarioIndexRouteImport } from './routes/jefe-zona/inventario/index'
import { Route as JefeZonaLiquidacionesIndexRouteImport } from './routes/jefe-zona/liquidaciones/index'
import { Route as JefeZonaVentasIndexRouteImport } from './routes/jefe-zona/ventas/index'
import { Route as AdminCatalogoCombosIndexRouteImport } from './routes/admin/catalogo/combos/index'
import { Route as AdminCatalogoParqueaderoIndexRouteImport } from './routes/admin/catalogo/parqueadero/index'
import { Route as AdminCatalogoServiciosIndexRouteImport } from './routes/admin/catalogo/servicios/index'
import { Route as AdminCatalogoTiposVehiculoIndexRouteImport } from './routes/admin/catalogo/tipos-vehiculo/index'
import { Route as AdminDineroGastosIndexRouteImport } from './routes/admin/dinero/gastos/index'
import { Route as AdminDineroInventarioIndexRouteImport } from './routes/admin/dinero/inventario/index'
import { Route as AdminDineroLiquidacionesIndexRouteImport } from './routes/admin/dinero/liquidaciones/index'
import { Route as AdminOperacionClientesIndexRouteImport } from './routes/admin/operacion/clientes/index'
import { Route as AdminOperacionOrdenesIndexRouteImport } from './routes/admin/operacion/ordenes/index'
import { Route as AdminOperacionTurnosIndexRouteImport } from './routes/admin/operacion/turnos/index'
import { Route as AdminPersonalLavadoresIndexRouteImport } from './routes/admin/personal/lavadores/index'
import { Route as AdminPersonalUsuariosIndexRouteImport } from './routes/admin/personal/usuarios/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const JefeZonaRouteRoute = JefeZonaRouteRouteImport.update({
  id: '/jefe-zona',
  path: '/jefe-zona',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcionRouteRoute = RecepcionRouteRouteImport.update({
  id: '/recepcion',
  path: '/recepcion',
  getParentRoute: () => rootRouteImport,
} as any)
const VigilanteRouteRoute = VigilanteRouteRouteImport.update({
  id: '/vigilante',
  path: '/vigilante',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCatalogoRouteRoute = AdminCatalogoRouteRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDineroRouteRoute = AdminDineroRouteRouteImport.update({
  id: '/dinero',
  path: '/dinero',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOperacionRouteRoute = AdminOperacionRouteRouteImport.update({
  id: '/operacion',
  path: '/operacion',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPersonalRouteRoute = AdminPersonalRouteRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AdminRouteRoute,
} as any)
const JefeZonaIndexRoute = JefeZonaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JefeZonaRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcionIndexRoute = RecepcionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecepcionRouteRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const VigilanteIndexRoute = VigilanteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VigilanteRouteRoute,
} as any)
const AdminCatalogoIndexRoute = AdminCatalogoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCatalogoRouteRoute,
} as any)
const AdminConfiguracionIndexRoute = AdminConfiguracionIndexRouteImport.update({
  id: '/configuracion/',
  path: '/configuracion/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDineroIndexRoute = AdminDineroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDineroRouteRoute,
} as any)
const AdminOperacionIndexRoute = AdminOperacionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOperacionRouteRoute,
} as any)
const AdminPersonalIndexRoute = AdminPersonalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPersonalRouteRoute,
} as any)
const JefeZonaAsistenciaIndexRoute = JefeZonaAsistenciaIndexRouteImport.update({
  id: '/asistencia/',
  path: '/asistencia/',
  getParentRoute: () => JefeZonaRouteRoute,
} as any)
const JefeZonaCajaIndexRoute = JefeZonaCajaIndexRouteImport.update({
  id: '/caja/',
  path: '/caja/',
  getParentRoute: () => JefeZonaRouteRoute,
} as any)
const JefeZonaInventarioIndexRoute = JefeZonaInventarioIndexRouteImport.update({
  id: '/inventario/',
  path: '/inventario/',
  getParentRoute: () => JefeZonaRouteRoute,
} as any)
const JefeZonaLiquidacionesIndexRoute =
  JefeZonaLiquidacionesIndexRouteImport.update({
    id: '/liquidaciones/',
    path: '/liquidaciones/',
    getParentRoute: () => JefeZonaRouteRoute,
  } as any)
const JefeZonaVentasIndexRoute = JefeZonaVentasIndexRouteImport.update({
  id: '/ventas/',
  path: '/ventas/',
  getParentRoute: () => JefeZonaRouteRoute,
} as any)
const AdminCatalogoCombosIndexRoute =
  AdminCatalogoCombosIndexRouteImport.update({
    id: '/combos/',
    path: '/combos/',
    getParentRoute: () => AdminCatalogoRouteRoute,
  } as any)
const AdminCatalogoParqueaderoIndexRoute =
  AdminCatalogoParqueaderoIndexRouteImport.update({
    id: '/parqueadero/',
    path: '/parqueadero/',
    getParentRoute: () => AdminCatalogoRouteRoute,
  } as any)
const AdminCatalogoServiciosIndexRoute =
  AdminCatalogoServiciosIndexRouteImport.update({
    id: '/servicios/',
    path: '/servicios/',
    getParentRoute: () => AdminCatalogoRouteRoute,
  } as any)
const AdminCatalogoTiposVehiculoIndexRoute =
  AdminCatalogoTiposVehiculoIndexRouteImport.update({
    id: '/tipos-vehiculo/',
    path: '/tipos-vehiculo/',
    getParentRoute: () => AdminCatalogoRouteRoute,
  } as any)
const AdminDineroGastosIndexRoute = AdminDineroGastosIndexRouteImport.update({
  id: '/gastos/',
  path: '/gastos/',
  getParentRoute: () => AdminDineroRouteRoute,
} as any)
const AdminDineroInventarioIndexRoute =
  AdminDineroInventarioIndexRouteImport.update({
    id: '/inventario/',
    path: '/inventario/',
    getParentRoute: () => AdminDineroRouteRoute,
  } as any)
const AdminDineroLiquidacionesIndexRoute =
  AdminDineroLiquidacionesIndexRouteImport.update({
    id: '/liquidaciones/',
    path: '/liquidaciones/',
    getParentRoute: () => AdminDineroRouteRoute,
  } as any)
const AdminOperacionClientesIndexRoute =
  AdminOperacionClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AdminOperacionRouteRoute,
  } as any)
const AdminOperacionOrdenesIndexRoute =
  AdminOperacionOrdenesIndexRouteImport.update({
    id: '/ordenes/',
    path: '/ordenes/',
    getParentRoute: () => AdminOperacionRouteRoute,
  } as any)
const AdminOperacionTurnosIndexRoute =
  AdminOperacionTurnosIndexRouteImport.update({
    id: '/turnos/',
    path: '/turnos/',
    getParentRoute: () => AdminOperacionRouteRoute,
  } as any)
const AdminPersonalLavadoresIndexRoute =
  AdminPersonalLavadoresIndexRouteImport.update({
    id: '/lavadores/',
    path: '/lavadores/',
    getParentRoute: () => AdminPersonalRouteRoute,
  } as any)
const AdminPersonalUsuariosIndexRoute =
  AdminPersonalUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AdminPersonalRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/jefe-zona': typeof JefeZonaRouteRouteWithChildren
  '/recepcion': typeof RecepcionRouteRouteWithChildren
  '/vigilante': typeof VigilanteRouteRouteWithChildren
  '/admin/catalogo': typeof AdminCatalogoRouteRouteWithChildren
  '/admin/dinero': typeof AdminDineroRouteRouteWithChildren
  '/admin/operacion': typeof AdminOperacionRouteRouteWithChildren
  '/admin/personal': typeof AdminPersonalRouteRouteWithChildren
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jefe-zona/': typeof JefeZonaIndexRoute
  '/login/': typeof LoginIndexRoute
  '/recepcion/': typeof RecepcionIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/vigilante/': typeof VigilanteIndexRoute
  '/admin/catalogo/': typeof AdminCatalogoIndexRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/dinero/': typeof AdminDineroIndexRoute
  '/admin/operacion/': typeof AdminOperacionIndexRoute
  '/admin/personal/': typeof AdminPersonalIndexRoute
  '/jefe-zona/asistencia/': typeof JefeZonaAsistenciaIndexRoute
  '/jefe-zona/caja/': typeof JefeZonaCajaIndexRoute
  '/jefe-zona/inventario/': typeof JefeZonaInventarioIndexRoute
  '/jefe-zona/liquidaciones/': typeof JefeZonaLiquidacionesIndexRoute
  '/jefe-zona/ventas/': typeof JefeZonaVentasIndexRoute
  '/admin/catalogo/combos/': typeof AdminCatalogoCombosIndexRoute
  '/admin/catalogo/parqueadero/': typeof AdminCatalogoParqueaderoIndexRoute
  '/admin/catalogo/servicios/': typeof AdminCatalogoServiciosIndexRoute
  '/admin/catalogo/tipos-vehiculo/': typeof AdminCatalogoTiposVehiculoIndexRoute
  '/admin/dinero/gastos/': typeof AdminDineroGastosIndexRoute
  '/admin/dinero/inventario/': typeof AdminDineroInventarioIndexRoute
  '/admin/dinero/liquidaciones/': typeof AdminDineroLiquidacionesIndexRoute
  '/admin/operacion/clientes/': typeof AdminOperacionClientesIndexRoute
  '/admin/operacion/ordenes/': typeof AdminOperacionOrdenesIndexRoute
  '/admin/operacion/turnos/': typeof AdminOperacionTurnosIndexRoute
  '/admin/personal/lavadores/': typeof AdminPersonalLavadoresIndexRoute
  '/admin/personal/usuarios/': typeof AdminPersonalUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/admin': typeof AdminIndexRoute
  '/jefe-zona': typeof JefeZonaIndexRoute
  '/login': typeof LoginIndexRoute
  '/recepcion': typeof RecepcionIndexRoute
  '/services': typeof ServicesIndexRoute
  '/vigilante': typeof VigilanteIndexRoute
  '/admin/catalogo': typeof AdminCatalogoIndexRoute
  '/admin/configuracion': typeof AdminConfiguracionIndexRoute
  '/admin/dinero': typeof AdminDineroIndexRoute
  '/admin/operacion': typeof AdminOperacionIndexRoute
  '/admin/personal': typeof AdminPersonalIndexRoute
  '/jefe-zona/asistencia': typeof JefeZonaAsistenciaIndexRoute
  '/jefe-zona/caja': typeof JefeZonaCajaIndexRoute
  '/jefe-zona/inventario': typeof JefeZonaInventarioIndexRoute
  '/jefe-zona/liquidaciones': typeof JefeZonaLiquidacionesIndexRoute
  '/jefe-zona/ventas': typeof JefeZonaVentasIndexRoute
  '/admin/catalogo/combos': typeof AdminCatalogoCombosIndexRoute
  '/admin/catalogo/parqueadero': typeof AdminCatalogoParqueaderoIndexRoute
  '/admin/catalogo/servicios': typeof AdminCatalogoServiciosIndexRoute
  '/admin/catalogo/tipos-vehiculo': typeof AdminCatalogoTiposVehiculoIndexRoute
  '/admin/dinero/gastos': typeof AdminDineroGastosIndexRoute
  '/admin/dinero/inventario': typeof AdminDineroInventarioIndexRoute
  '/admin/dinero/liquidaciones': typeof AdminDineroLiquidacionesIndexRoute
  '/admin/operacion/clientes': typeof AdminOperacionClientesIndexRoute
  '/admin/operacion/ordenes': typeof AdminOperacionOrdenesIndexRoute
  '/admin/operacion/turnos': typeof AdminOperacionTurnosIndexRoute
  '/admin/personal/lavadores': typeof AdminPersonalLavadoresIndexRoute
  '/admin/personal/usuarios': typeof AdminPersonalUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/jefe-zona': typeof JefeZonaRouteRouteWithChildren
  '/recepcion': typeof RecepcionRouteRouteWithChildren
  '/vigilante': typeof VigilanteRouteRouteWithChildren
  '/admin/catalogo': typeof AdminCatalogoRouteRouteWithChildren
  '/admin/dinero': typeof AdminDineroRouteRouteWithChildren
  '/admin/operacion': typeof AdminOperacionRouteRouteWithChildren
  '/admin/personal': typeof AdminPersonalRouteRouteWithChildren
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jefe-zona/': typeof JefeZonaIndexRoute
  '/login/': typeof LoginIndexRoute
  '/recepcion/': typeof RecepcionIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/vigilante/': typeof VigilanteIndexRoute
  '/admin/catalogo/': typeof AdminCatalogoIndexRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/dinero/': typeof AdminDineroIndexRoute
  '/admin/operacion/': typeof AdminOperacionIndexRoute
  '/admin/personal/': typeof AdminPersonalIndexRoute
  '/jefe-zona/asistencia/': typeof JefeZonaAsistenciaIndexRoute
  '/jefe-zona/caja/': typeof JefeZonaCajaIndexRoute
  '/jefe-zona/inventario/': typeof JefeZonaInventarioIndexRoute
  '/jefe-zona/liquidaciones/': typeof JefeZonaLiquidacionesIndexRoute
  '/jefe-zona/ventas/': typeof JefeZonaVentasIndexRoute
  '/admin/catalogo/combos/': typeof AdminCatalogoCombosIndexRoute
  '/admin/catalogo/parqueadero/': typeof AdminCatalogoParqueaderoIndexRoute
  '/admin/catalogo/servicios/': typeof AdminCatalogoServiciosIndexRoute
  '/admin/catalogo/tipos-vehiculo/': typeof AdminCatalogoTiposVehiculoIndexRoute
  '/admin/dinero/gastos/': typeof AdminDineroGastosIndexRoute
  '/admin/dinero/inventario/': typeof AdminDineroInventarioIndexRoute
  '/admin/dinero/liquidaciones/': typeof AdminDineroLiquidacionesIndexRoute
  '/admin/operacion/clientes/': typeof AdminOperacionClientesIndexRoute
  '/admin/operacion/ordenes/': typeof AdminOperacionOrdenesIndexRoute
  '/admin/operacion/turnos/': typeof AdminOperacionTurnosIndexRoute
  '/admin/personal/lavadores/': typeof AdminPersonalLavadoresIndexRoute
  '/admin/personal/usuarios/': typeof AdminPersonalUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/jefe-zona'
    | '/recepcion'
    | '/vigilante'
    | '/admin/catalogo'
    | '/admin/dinero'
    | '/admin/operacion'
    | '/admin/personal'
    | '/services/$serviceId'
    | '/admin/'
    | '/jefe-zona/'
    | '/login/'
    | '/recepcion/'
    | '/services/'
    | '/vigilante/'
    | '/admin/catalogo/'
    | '/admin/configuracion/'
    | '/admin/dinero/'
    | '/admin/operacion/'
    | '/admin/personal/'
    | '/jefe-zona/asistencia/'
    | '/jefe-zona/caja/'
    | '/jefe-zona/inventario/'
    | '/jefe-zona/liquidaciones/'
    | '/jefe-zona/ventas/'
    | '/admin/catalogo/combos/'
    | '/admin/catalogo/parqueadero/'
    | '/admin/catalogo/servicios/'
    | '/admin/catalogo/tipos-vehiculo/'
    | '/admin/dinero/gastos/'
    | '/admin/dinero/inventario/'
    | '/admin/dinero/liquidaciones/'
    | '/admin/operacion/clientes/'
    | '/admin/operacion/ordenes/'
    | '/admin/operacion/turnos/'
    | '/admin/personal/lavadores/'
    | '/admin/personal/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services/$serviceId'
    | '/admin'
    | '/jefe-zona'
    | '/login'
    | '/recepcion'
    | '/services'
    | '/vigilante'
    | '/admin/catalogo'
    | '/admin/configuracion'
    | '/admin/dinero'
    | '/admin/operacion'
    | '/admin/personal'
    | '/jefe-zona/asistencia'
    | '/jefe-zona/caja'
    | '/jefe-zona/inventario'
    | '/jefe-zona/liquidaciones'
    | '/jefe-zona/ventas'
    | '/admin/catalogo/combos'
    | '/admin/catalogo/parqueadero'
    | '/admin/catalogo/servicios'
    | '/admin/catalogo/tipos-vehiculo'
    | '/admin/dinero/gastos'
    | '/admin/dinero/inventario'
    | '/admin/dinero/liquidaciones'
    | '/admin/operacion/clientes'
    | '/admin/operacion/ordenes'
    | '/admin/operacion/turnos'
    | '/admin/personal/lavadores'
    | '/admin/personal/usuarios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/jefe-zona'
    | '/recepcion'
    | '/vigilante'
    | '/admin/catalogo'
    | '/admin/dinero'
    | '/admin/operacion'
    | '/admin/personal'
    | '/services/$serviceId'
    | '/admin/'
    | '/jefe-zona/'
    | '/login/'
    | '/recepcion/'
    | '/services/'
    | '/vigilante/'
    | '/admin/catalogo/'
    | '/admin/configuracion/'
    | '/admin/dinero/'
    | '/admin/operacion/'
    | '/admin/personal/'
    | '/jefe-zona/asistencia/'
    | '/jefe-zona/caja/'
    | '/jefe-zona/inventario/'
    | '/jefe-zona/liquidaciones/'
    | '/jefe-zona/ventas/'
    | '/admin/catalogo/combos/'
    | '/admin/catalogo/parqueadero/'
    | '/admin/catalogo/servicios/'
    | '/admin/catalogo/tipos-vehiculo/'
    | '/admin/dinero/gastos/'
    | '/admin/dinero/inventario/'
    | '/admin/dinero/liquidaciones/'
    | '/admin/operacion/clientes/'
    | '/admin/operacion/ordenes/'
    | '/admin/operacion/turnos/'
    | '/admin/personal/lavadores/'
    | '/admin/personal/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  JefeZonaRouteRoute: typeof JefeZonaRouteRouteWithChildren
  RecepcionRouteRoute: typeof RecepcionRouteRouteWithChildren
  VigilanteRouteRoute: typeof VigilanteRouteRouteWithChildren
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jefe-zona': {
      id: '/jefe-zona'
      path: '/jefe-zona'
      fullPath: '/jefe-zona'
      preLoaderRoute: typeof JefeZonaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcion': {
      id: '/recepcion'
      path: '/recepcion'
      fullPath: '/recepcion'
      preLoaderRoute: typeof RecepcionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vigilante': {
      id: '/vigilante'
      path: '/vigilante'
      fullPath: '/vigilante'
      preLoaderRoute: typeof VigilanteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalogo': {
      id: '/admin/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminCatalogoRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dinero': {
      id: '/admin/dinero'
      path: '/dinero'
      fullPath: '/admin/dinero'
      preLoaderRoute: typeof AdminDineroRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/operacion': {
      id: '/admin/operacion'
      path: '/operacion'
      fullPath: '/admin/operacion'
      preLoaderRoute: typeof AdminOperacionRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/personal': {
      id: '/admin/personal'
      path: '/personal'
      fullPath: '/admin/personal'
      preLoaderRoute: typeof AdminPersonalRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/jefe-zona/': {
      id: '/jefe-zona/'
      path: '/'
      fullPath: '/jefe-zona/'
      preLoaderRoute: typeof JefeZonaIndexRouteImport
      parentRoute: typeof JefeZonaRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcion/': {
      id: '/recepcion/'
      path: '/'
      fullPath: '/recepcion/'
      preLoaderRoute: typeof RecepcionIndexRouteImport
      parentRoute: typeof RecepcionRouteRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vigilante/': {
      id: '/vigilante/'
      path: '/'
      fullPath: '/vigilante/'
      preLoaderRoute: typeof VigilanteIndexRouteImport
      parentRoute: typeof VigilanteRouteRoute
    }
    '/admin/catalogo/': {
      id: '/admin/catalogo/'
      path: '/'
      fullPath: '/admin/catalogo/'
      preLoaderRoute: typeof AdminCatalogoIndexRouteImport
      parentRoute: typeof AdminCatalogoRouteRoute
    }
    '/admin/configuracion/': {
      id: '/admin/configuracion/'
      path: '/configuracion'
      fullPath: '/admin/configuracion/'
      preLoaderRoute: typeof AdminConfiguracionIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dinero/': {
      id: '/admin/dinero/'
      path: '/'
      fullPath: '/admin/dinero/'
      preLoaderRoute: typeof AdminDineroIndexRouteImport
      parentRoute: typeof AdminDineroRouteRoute
    }
    '/admin/operacion/': {
      id: '/admin/operacion/'
      path: '/'
      fullPath: '/admin/operacion/'
      preLoaderRoute: typeof AdminOperacionIndexRouteImport
      parentRoute: typeof AdminOperacionRouteRoute
    }
    '/admin/personal/': {
      id: '/admin/personal/'
      path: '/'
      fullPath: '/admin/personal/'
      preLoaderRoute: typeof AdminPersonalIndexRouteImport
      parentRoute: typeof AdminPersonalRouteRoute
    }
    '/jefe-zona/asistencia/': {
      id: '/jefe-zona/asistencia/'
      path: '/asistencia'
      fullPath: '/jefe-zona/asistencia/'
      preLoaderRoute: typeof JefeZonaAsistenciaIndexRouteImport
      parentRoute: typeof JefeZonaRouteRoute
    }
    '/jefe-zona/caja/': {
      id: '/jefe-zona/caja/'
      path: '/caja'
      fullPath: '/jefe-zona/caja/'
      preLoaderRoute: typeof JefeZonaCajaIndexRouteImport
      parentRoute: typeof JefeZonaRouteRoute
    }
    '/jefe-zona/inventario/': {
      id: '/jefe-zona/inventario/'
      path: '/inventario'
      fullPath: '/jefe-zona/inventario/'
      preLoaderRoute: typeof JefeZonaInventarioIndexRouteImport
      parentRoute: typeof JefeZonaRouteRoute
    }
    '/jefe-zona/liquidaciones/': {
      id: '/jefe-zona/liquidaciones/'
      path: '/liquidaciones'
      fullPath: '/jefe-zona/liquidaciones/'
      preLoaderRoute: typeof JefeZonaLiquidacionesIndexRouteImport
      parentRoute: typeof JefeZonaRouteRoute
    }
    '/jefe-zona/ventas/': {
      id: '/jefe-zona/ventas/'
      path: '/ventas'
      fullPath: '/jefe-zona/ventas/'
      preLoaderRoute: typeof JefeZonaVentasIndexRouteImport
      parentRoute: typeof JefeZonaRouteRoute
    }
    '/admin/catalogo/combos/': {
      id: '/admin/catalogo/combos/'
      path: '/combos'
      fullPath: '/admin/catalogo/combos/'
      preLoaderRoute: typeof AdminCatalogoCombosIndexRouteImport
      parentRoute: typeof AdminCatalogoRouteRoute
    }
    '/admin/catalogo/parqueadero/': {
      id: '/admin/catalogo/parqueadero/'
      path: '/parqueadero'
      fullPath: '/admin/catalogo/parqueadero/'
      preLoaderRoute: typeof AdminCatalogoParqueaderoIndexRouteImport
      parentRoute: typeof AdminCatalogoRouteRoute
    }
    '/admin/catalogo/servicios/': {
      id: '/admin/catalogo/servicios/'
      path: '/servicios'
      fullPath: '/admin/catalogo/servicios/'
      preLoaderRoute: typeof AdminCatalogoServiciosIndexRouteImport
      parentRoute: typeof AdminCatalogoRouteRoute
    }
    '/admin/catalogo/tipos-vehiculo/': {
      id: '/admin/catalogo/tipos-vehiculo/'
      path: '/tipos-vehiculo'
      fullPath: '/admin/catalogo/tipos-vehiculo/'
      preLoaderRoute: typeof AdminCatalogoTiposVehiculoIndexRouteImport
      parentRoute: typeof AdminCatalogoRouteRoute
    }
    '/admin/dinero/gastos/': {
      id: '/admin/dinero/gastos/'
      path: '/gastos'
      fullPath: '/admin/dinero/gastos/'
      preLoaderRoute: typeof AdminDineroGastosIndexRouteImport
      parentRoute: typeof AdminDineroRouteRoute
    }
    '/admin/dinero/inventario/': {
      id: '/admin/dinero/inventario/'
      path: '/inventario'
      fullPath: '/admin/dinero/inventario/'
      preLoaderRoute: typeof AdminDineroInventarioIndexRouteImport
      parentRoute: typeof AdminDineroRouteRoute
    }
    '/admin/dinero/liquidaciones/': {
      id: '/admin/dinero/liquidaciones/'
      path: '/liquidaciones'
      fullPath: '/admin/dinero/liquidaciones/'
      preLoaderRoute: typeof AdminDineroLiquidacionesIndexRouteImport
      parentRoute: typeof AdminDineroRouteRoute
    }
    '/admin/operacion/clientes/': {
      id: '/admin/operacion/clientes/'
      path: '/clientes'
      fullPath: '/admin/operacion/clientes/'
      preLoaderRoute: typeof AdminOperacionClientesIndexRouteImport
      parentRoute: typeof AdminOperacionRouteRoute
    }
    '/admin/operacion/ordenes/': {
      id: '/admin/operacion/ordenes/'
      path: '/ordenes'
      fullPath: '/admin/operacion/ordenes/'
      preLoaderRoute: typeof AdminOperacionOrdenesIndexRouteImport
      parentRoute: typeof AdminOperacionRouteRoute
    }
    '/admin/operacion/turnos/': {
      id: '/admin/operacion/turnos/'
      path: '/turnos'
      fullPath: '/admin/operacion/turnos/'
      preLoaderRoute: typeof AdminOperacionTurnosIndexRouteImport
      parentRoute: typeof AdminOperacionRouteRoute
    }
    '/admin/personal/lavadores/': {
      id: '/admin/personal/lavadores/'
      path: '/lavadores'
      fullPath: '/admin/personal/lavadores/'
      preLoaderRoute: typeof AdminPersonalLavadoresIndexRouteImport
      parentRoute: typeof AdminPersonalRouteRoute
    }
    '/admin/personal/usuarios/': {
      id: '/admin/personal/usuarios/'
      path: '/usuarios'
      fullPath: '/admin/personal/usuarios/'
      preLoaderRoute: typeof AdminPersonalUsuariosIndexRouteImport
      parentRoute: typeof AdminPersonalRouteRoute
    }
  }
}

interface AdminCatalogoRouteRouteChildren {
  AdminCatalogoIndexRoute: typeof AdminCatalogoIndexRoute
  AdminCatalogoCombosIndexRoute: typeof AdminCatalogoCombosIndexRoute
  AdminCatalogoParqueaderoIndexRoute: typeof AdminCatalogoParqueaderoIndexRoute
  AdminCatalogoServiciosIndexRoute: typeof AdminCatalogoServiciosIndexRoute
  AdminCatalogoTiposVehiculoIndexRoute: typeof AdminCatalogoTiposVehiculoIndexRoute
}

const AdminCatalogoRouteRouteChildren: AdminCatalogoRouteRouteChildren = {
  AdminCatalogoIndexRoute: AdminCatalogoIndexRoute,
  AdminCatalogoCombosIndexRoute: AdminCatalogoCombosIndexRoute,
  AdminCatalogoParqueaderoIndexRoute: AdminCatalogoParqueaderoIndexRoute,
  AdminCatalogoServiciosIndexRoute: AdminCatalogoServiciosIndexRoute,
  AdminCatalogoTiposVehiculoIndexRoute: AdminCatalogoTiposVehiculoIndexRoute,
}

const AdminCatalogoRouteRouteWithChildren =
  AdminCatalogoRouteRoute._addFileChildren(AdminCatalogoRouteRouteChildren)

interface AdminDineroRouteRouteChildren {
  AdminDineroIndexRoute: typeof AdminDineroIndexRoute
  AdminDineroGastosIndexRoute: typeof AdminDineroGastosIndexRoute
  AdminDineroInventarioIndexRoute: typeof AdminDineroInventarioIndexRoute
  AdminDineroLiquidacionesIndexRoute: typeof AdminDineroLiquidacionesIndexRoute
}

const AdminDineroRouteRouteChildren: AdminDineroRouteRouteChildren = {
  AdminDineroIndexRoute: AdminDineroIndexRoute,
  AdminDineroGastosIndexRoute: AdminDineroGastosIndexRoute,
  AdminDineroInventarioIndexRoute: AdminDineroInventarioIndexRoute,
  AdminDineroLiquidacionesIndexRoute: AdminDineroLiquidacionesIndexRoute,
}

const AdminDineroRouteRouteWithChildren =
  AdminDineroRouteRoute._addFileChildren(AdminDineroRouteRouteChildren)

interface AdminOperacionRouteRouteChildren {
  AdminOperacionIndexRoute: typeof AdminOperacionIndexRoute
  AdminOperacionClientesIndexRoute: typeof AdminOperacionClientesIndexRoute
  AdminOperacionOrdenesIndexRoute: typeof AdminOperacionOrdenesIndexRoute
  AdminOperacionTurnosIndexRoute: typeof AdminOperacionTurnosIndexRoute
}

const AdminOperacionRouteRouteChildren: AdminOperacionRouteRouteChildren = {
  AdminOperacionIndexRoute: AdminOperacionIndexRoute,
  AdminOperacionClientesIndexRoute: AdminOperacionClientesIndexRoute,
  AdminOperacionOrdenesIndexRoute: AdminOperacionOrdenesIndexRoute,
  AdminOperacionTurnosIndexRoute: AdminOperacionTurnosIndexRoute,
}

const AdminOperacionRouteRouteWithChildren =
  AdminOperacionRouteRoute._addFileChildren(AdminOperacionRouteRouteChildren)

interface AdminPersonalRouteRouteChildren {
  AdminPersonalIndexRoute: typeof AdminPersonalIndexRoute
  AdminPersonalLavadoresIndexRoute: typeof AdminPersonalLavadoresIndexRoute
  AdminPersonalUsuariosIndexRoute: typeof AdminPersonalUsuariosIndexRoute
}

const AdminPersonalRouteRouteChildren: AdminPersonalRouteRouteChildren = {
  AdminPersonalIndexRoute: AdminPersonalIndexRoute,
  AdminPersonalLavadoresIndexRoute: AdminPersonalLavadoresIndexRoute,
  AdminPersonalUsuariosIndexRoute: AdminPersonalUsuariosIndexRoute,
}

const AdminPersonalRouteRouteWithChildren =
  AdminPersonalRouteRoute._addFileChildren(AdminPersonalRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminCatalogoRouteRoute: typeof AdminCatalogoRouteRouteWithChildren
  AdminDineroRouteRoute: typeof AdminDineroRouteRouteWithChildren
  AdminOperacionRouteRoute: typeof AdminOperacionRouteRouteWithChildren
  AdminPersonalRouteRoute: typeof AdminPersonalRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConfiguracionIndexRoute: typeof AdminConfiguracionIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCatalogoRouteRoute: AdminCatalogoRouteRouteWithChildren,
  AdminDineroRouteRoute: AdminDineroRouteRouteWithChildren,
  AdminOperacionRouteRoute: AdminOperacionRouteRouteWithChildren,
  AdminPersonalRouteRoute: AdminPersonalRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminConfiguracionIndexRoute: AdminConfiguracionIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface JefeZonaRouteRouteChildren {
  JefeZonaIndexRoute: typeof JefeZonaIndexRoute
  JefeZonaAsistenciaIndexRoute: typeof JefeZonaAsistenciaIndexRoute
  JefeZonaCajaIndexRoute: typeof JefeZonaCajaIndexRoute
  JefeZonaInventarioIndexRoute: typeof JefeZonaInventarioIndexRoute
  JefeZonaLiquidacionesIndexRoute: typeof JefeZonaLiquidacionesIndexRoute
  JefeZonaVentasIndexRoute: typeof JefeZonaVentasIndexRoute
}

const JefeZonaRouteRouteChildren: JefeZonaRouteRouteChildren = {
  JefeZonaIndexRoute: JefeZonaIndexRoute,
  JefeZonaAsistenciaIndexRoute: JefeZonaAsistenciaIndexRoute,
  JefeZonaCajaIndexRoute: JefeZonaCajaIndexRoute,
  JefeZonaInventarioIndexRoute: JefeZonaInventarioIndexRoute,
  JefeZonaLiquidacionesIndexRoute: JefeZonaLiquidacionesIndexRoute,
  JefeZonaVentasIndexRoute: JefeZonaVentasIndexRoute,
}

const JefeZonaRouteRouteWithChildren = JefeZonaRouteRoute._addFileChildren(
  JefeZonaRouteRouteChildren,
)

interface RecepcionRouteRouteChildren {
  RecepcionIndexRoute: typeof RecepcionIndexRoute
}

const RecepcionRouteRouteChildren: RecepcionRouteRouteChildren = {
  RecepcionIndexRoute: RecepcionIndexRoute,
}

const RecepcionRouteRouteWithChildren = RecepcionRouteRoute._addFileChildren(
  RecepcionRouteRouteChildren,
)

interface VigilanteRouteRouteChildren {
  VigilanteIndexRoute: typeof VigilanteIndexRoute
}

const VigilanteRouteRouteChildren: VigilanteRouteRouteChildren = {
  VigilanteIndexRoute: VigilanteIndexRoute,
}

const VigilanteRouteRouteWithChildren = VigilanteRouteRoute._addFileChildren(
  VigilanteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  JefeZonaRouteRoute: JefeZonaRouteRouteWithChildren,
  RecepcionRouteRoute: RecepcionRouteRouteWithChildren,
  VigilanteRouteRoute: VigilanteRouteRouteWithChildren,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
